package com.cssl.ctp.il.wsdl.mobileelectronictopup_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;
import com.cssl.ctp.il.xsd.csheaders_v1.RequestHeaderType;
import com.cssl.ctp.il.xsd.csheaders_v1.ResponseHeaderType;
import com.cssl.ctp.il.xsd.mobileelectronictopup_v1.MobileElectronicTopUpRequestBodyType;
import com.cssl.ctp.il.xsd.mobileelectronictopup_v1.MobileElectronicTopUpResponseBodyType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MobileElectronicTopUpPortType_v1_0", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileElectronicTopUp-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MobileElectronicTopUpPortTypeV10 {

	/**
	 * 
	 * @param requestBody
	 * @param responseHeader
	 * @param responseBody
	 * @param requestHeader
	 * @throws Fault
	 */
	@WebMethod(operationName = "MobileElectronicTopUp")
	public void mobileElectronicTopUp(
			@WebParam(name = "RequestHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileElectronicTopUp-v1.0", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
			@WebParam(name = "MobileElectronicTopUpRequest", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileElectronicTopUp-v1.0", partName = "requestBody") MobileElectronicTopUpRequestBodyType requestBody,
			@WebParam(name = "ResponseHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileElectronicTopUp-v1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader,
			@WebParam(name = "MobileElectronicTopUpResponse", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileElectronicTopUp-v1.0", mode = WebParam.Mode.OUT, partName = "responseBody") Holder<MobileElectronicTopUpResponseBodyType> responseBody)
			throws Fault;

}
