package com.cssl.ctp.il.wsdl.refund_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;
import com.cssl.ctp.il.xsd.csheaders_v1.RequestHeaderType;
import com.cssl.ctp.il.xsd.csheaders_v1.ResponseHeaderType;
import com.cssl.ctp.il.xsd.refund_v1.RefundRequestBodyType;
import com.cssl.ctp.il.xsd.refund_v1.RefundResponseBodyType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RefundPortType_v1_0", targetNamespace = "http://ctp.cssl.com/il/wsdl/Refund-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RefundPortTypeV10 {

	/**
	 * 
	 * @param requestBody
	 * @param responseHeader
	 * @param responseBody
	 * @param requestHeader
	 * @throws Fault
	 */
	@WebMethod(operationName = "Refund")
	public void refund(
			@WebParam(name = "RequestHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/Refund-v1.0", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
			@WebParam(name = "RefundRequest", targetNamespace = "http://ctp.cssl.com/il/wsdl/Refund-v1.0", partName = "requestBody") RefundRequestBodyType requestBody,
			@WebParam(name = "ResponseHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/Refund-v1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader,
			@WebParam(name = "RefundResponse", targetNamespace = "http://ctp.cssl.com/il/wsdl/Refund-v1.0", mode = WebParam.Mode.OUT, partName = "responseBody") Holder<RefundResponseBodyType> responseBody)
			throws Fault;

}
