package com.cssl.ctp.il.wsdl.refund_v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.skilrock.lms.common.utility.PropertyLoader;



/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RefundBinding_v1_0 service = new RefundBinding_v1_0();
 * RefundPortTypeV10 portType = service.getPARTNER();
 * portType.refund(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RefundBinding_v1_0", targetNamespace = "http://ctp.cssl.com/il/wsdl/Refund-v1", wsdlLocation = "")
public class RefundBindingV10 extends Service {

	private final static URL REFUNDBINDINGV10_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.cssl.ctp.il.wsdl.refund_v1.RefundBindingV10.class
					.getName());
	private final static String wsdlPath;

	static {
		PropertyLoader.loadProperties("config/LMS.properties");
		wsdlPath = PropertyLoader.getProperty("CTP_WSDL_PATH");
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.cssl.ctp.il.wsdl.refund_v1.RefundBindingV10.class
					.getResource(".");
			url = new URL(
					baseUrl,
					wsdlPath+"Refund-v1.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: '"+ wsdlPath +"Refund-v1.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		REFUNDBINDINGV10_WSDL_LOCATION = url;
	}

	public RefundBindingV10(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RefundBindingV10() {
		super(REFUNDBINDINGV10_WSDL_LOCATION, new QName(
				"http://ctp.cssl.com/il/wsdl/Refund-v1", "RefundBinding_v1_0"));
	}

	/**
	 * 
	 * @return returns RefundPortTypeV10
	 */
	@WebEndpoint(name = "PARTNER")
	public RefundPortTypeV10 getPARTNER() {
		return super.getPort(new QName("http://ctp.cssl.com/il/wsdl/Refund-v1",
				"PARTNER"), RefundPortTypeV10.class);
	}

}
