--liquibase formatted sql

-- changeset Ishu:1 endDelimiter:#
DROP PROCEDURE IF EXISTS `insDelArch`#

CREATE DEFINER=`root`@`localhost` PROCEDURE `insDelArch`(startDate TIMESTAMP,endDate TIMESTAMP,archDBName VARCHAR(50))
BEGIN
	DECLARE done INT DEFAULT 0;
	DECLARE gameId INT DEFAULT 0;
	DECLARE min_txn_id BIGINT(20);
	DECLARE max_txn_id BIGINT(20);
	DECLARE gameDGCur CURSOR FOR SELECT game_id  FROM st_dg_game_master;
	DECLARE catCSCur CURSOR FOR SELECT category_id  FROM st_cs_product_category_master;
	DECLARE  CONTINUE HANDLER FOR NOT FOUND SET done=1;
	
	SET @temp_retailer_id=CONCAT("delete from temp_arch_trans_retailer");
	PREPARE stmt FROM @temp_retailer_id;
	EXECUTE stmt;
	SET @temp_agent_id=CONCAT("delete from temp_arch_trans_agent");
	PREPARE stmt FROM @temp_agent_id;
	EXECUTE stmt;
	SET @temp_bo_id=CONCAT("delete from temp_arch_trans_bo");
	PREPARE stmt FROM @temp_bo_id;
	EXECUTE stmt;
	SET @temp_agent_receipt_id=CONCAT("delete from temp_arch_rec_agent");
	PREPARE stmt FROM @temp_agent_receipt_id;
	EXECUTE stmt;
	
	SET @temp_bo_receipt_id=CONCAT("delete from temp_arch_rec_bo");
	PREPARE stmt FROM @temp_bo_receipt_id;
	EXECUTE stmt; 
   SELECT 'tempFill';
   
    SET @isOLA:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='OLA');
	IF(@isOLA) THEN
	SET @olaRetDep=CONCAT("insert into ",archDBName,".st_ola_ret_deposit select * from st_ola_ret_deposit where transaction_id in ( select transaction_id from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT') ");
	PREPARE stmt FROM @olaRetDep;
	EXECUTE stmt;
	SET @olaDelRetDep=CONCAT("delete retDep from st_ola_ret_deposit retDep	inner  join st_lms_retailer_transaction_master slrm on slrm.transaction_id=	retDep.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT' " );
	PREPARE stmt FROM @olaDelRetDep;
	EXECUTE stmt;
	SET @olaRetDepRef=CONCAT("insert into ",archDBName,".st_ola_ret_deposit_refund select * from st_ola_ret_deposit_refund where transaction_id in ( select transaction_id from st_lms_retailer_transaction_master  where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND') " );
	PREPARE stmt FROM @olaRetDepRef;
	EXECUTE stmt;
	SET @olaDelRetDepRef=CONCAT("delete retDepRef from    st_ola_ret_deposit_refund retDepRef inner  join st_lms_retailer_transaction_master slrm on slrm.transaction_id=retDepRef.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND' " );
	PREPARE stmt FROM @olaDelRetDepRef;
	EXECUTE stmt;
	SET @olaRetWith=CONCAT("insert into ",archDBName,".st_ola_ret_withdrawl select * from  st_ola_ret_withdrawl where transaction_id in  (select transaction_id from st_lms_retailer_transaction_master  where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL' )" );
	PREPARE stmt FROM @olaRetWith;
	EXECUTE stmt;
	SET @olaDelRetWith=CONCAT("delete retWith  from   st_ola_ret_withdrawl retWith inner  join st_lms_retailer_transaction_master slrm on slrm.transaction_id=retWith.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL' " );
	PREPARE stmt FROM @olaDelRetWith;
	EXECUTE stmt;	
	SET @olaRetComm=CONCAT("insert into ",archDBName,".st_ola_ret_comm select * from st_ola_ret_comm where transaction_id in  (select transaction_id from st_lms_retailer_transaction_master  where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_COMMISSION' ) ");
	PREPARE stmt FROM @olaRetComm;
	EXECUTE stmt;
	SET @olaDelRetComm=CONCAT("delete retComm  from   st_ola_ret_comm retComm inner  join st_lms_retailer_transaction_master slrm on slrm.transaction_id=retComm.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_COMMISSION' " );
	PREPARE stmt FROM @olaDelRetComm;
	EXECUTE stmt;
	SET @olaAgtDep=CONCAT(" insert into ",archDBName,".st_ola_agt_deposit select * from  st_ola_agt_deposit where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT' ) " );
	PREPARE stmt FROM @olaAgtDep;
	EXECUTE stmt;
	SET @olaDelAgtDep=CONCAT("delete agtDep from st_ola_agt_deposit agtDep inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtDep.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT' " );
	PREPARE stmt FROM @olaDelAgtDep;
	EXECUTE stmt;	
	SET @olaAgtDepRef=CONCAT("insert into ",archDBName,".st_ola_agt_deposit_refund select * from  st_ola_agt_deposit_refund where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND' )" );
	PREPARE stmt FROM @olaAgtDepRef;
	EXECUTE stmt;
	SET @olaDelAgtDepRef=CONCAT("delete agtDepRef from st_ola_agt_deposit_refund agtDepRef inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtDepRef.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND' " );
	PREPARE stmt FROM @olaDelAgtDepRef;
	EXECUTE stmt;
	SET @olaAgtWith=CONCAT("insert into ",archDBName,".st_ola_agt_withdrawl select * from  st_ola_agt_withdrawl where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL' )" );
	PREPARE stmt FROM @olaAgtWith;
	EXECUTE stmt;
	SET @olaDelAgtWith=CONCAT("delete agtWith from st_ola_agt_withdrawl agtWith inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtWith.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL' " );
	PREPARE stmt FROM @olaDelAgtWith;
	EXECUTE stmt;
	SET @olaAgtComm=CONCAT("insert into ",archDBName,".st_ola_agt_comm select * from  st_ola_agt_comm where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_COMMISSION' ) " );
	PREPARE stmt FROM @olaAgtComm;
	EXECUTE stmt;
	SET @olaDelAgtComm=CONCAT("delete agtComm from st_ola_agt_comm agtComm inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtComm.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_COMMISSION' " );
	PREPARE stmt FROM @olaDelAgtComm;
	EXECUTE stmt;
	SET @olaAgtDepDirPlr=CONCAT(" insert into ",archDBName,".st_ola_agt_direct_plr_deposit select * from  st_ola_agt_direct_plr_deposit where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_PLR' ) " );
	PREPARE stmt FROM @olaAgtDepDirPlr;
	EXECUTE stmt;
	SET @olaDelAgtDepDirPlr=CONCAT("delete agtDepDirPlr from st_ola_agt_direct_plr_deposit agtDepDirPlr inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtDepDirPlr.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_PLR' " );
	PREPARE stmt FROM @olaDelAgtDepDirPlr;
	EXECUTE stmt;	
	SET @olaAgtDepRefDirPlr=CONCAT("insert into ",archDBName,".st_ola_agt_direct_plr_deposit_refund select * from  st_ola_agt_direct_plr_deposit_refund where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND_PLR' )" );
	PREPARE stmt FROM @olaAgtDepRefDirPlr;
	EXECUTE stmt;
	SET @olaDelAgtDepRefDirPlr=CONCAT("delete agtDepRef from st_ola_agt_deposit_refund agtDepRef inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtDepRef.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND_PLR' " );
	PREPARE stmt FROM @olaDelAgtDepRefDirPlr;
	EXECUTE stmt;
	SET @olaAgtWithDirPlr=CONCAT("insert into ",archDBName,".st_ola_agt_direct_plr_withdrawl select * from  st_ola_agt_direct_plr_withdrawl where transaction_id in(select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL_PLR' )" );
	PREPARE stmt FROM @olaAgtWithDirPlr;
	EXECUTE stmt;
	SET @olaDelAgtWithDirPlr=CONCAT("delete agtWith from st_ola_agt_direct_plr_withdrawl agtWith inner  join st_lms_agent_transaction_master slam on slam.transaction_id= agtWith.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL_PLR' " );
	PREPARE stmt FROM @olaDelAgtWithDirPlr;
	EXECUTE stmt;
	SET @olaBoDep=CONCAT("insert into ",archDBName,".st_ola_bo_deposit select * from st_ola_bo_deposit where transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT' )"); 
	PREPARE stmt FROM @olaBoDep;
	EXECUTE stmt;
	
	SET @olaDelBoDep=CONCAT(" delete boDep  from st_ola_bo_deposit boDep inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boDep.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT' " );
	PREPARE stmt FROM @olaDelBoDep;
	EXECUTE stmt;
	SET @olaBoDepRef=CONCAT("insert into ",archDBName,".st_ola_bo_deposit_refund select * from  st_ola_bo_deposit_refund where transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND' )" );
	PREPARE stmt FROM @olaBoDepRef;
	EXECUTE stmt;
	SET @olaDelBoDepRef=CONCAT("delete  boDepRef from    st_ola_bo_deposit_refund boDepRef inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boDepRef.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND' " );
	PREPARE stmt FROM @olaDelBoDepRef;
	EXECUTE stmt;
	SET @olaBoWith=CONCAT("insert into ",archDBName,".st_ola_bo_withdrawl select * from  st_ola_bo_withdrawl where transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL' )" );
	PREPARE stmt FROM @olaBoWith;
	EXECUTE stmt;
	SET @olaDelBoWith=CONCAT("delete boWith from  st_ola_bo_withdrawl boWith inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boWith.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL' " );
	PREPARE stmt FROM @olaDelBoWith;
	EXECUTE stmt;
	SET @olaBoComm=CONCAT("insert into ",archDBName,".st_ola_bo_comm select * from  st_ola_bo_comm  where transaction_id in(select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_COMMISSION' )" );
	PREPARE stmt FROM @olaBoComm;
	EXECUTE stmt;
	SET @olaDelBoComm=CONCAT("delete boComm from   st_ola_bo_comm boComm inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boComm .transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_COMMISSION' " );
	PREPARE stmt FROM @olaDelBoComm;
	EXECUTE stmt;
	SET @olaBoDepDirPlr=CONCAT("insert into ",archDBName,".st_ola_bo_direct_plr_deposit select * from st_ola_bo_direct_plr_deposit where transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_PLR' )"); 
	PREPARE stmt FROM @olaBoDepDirPlr;
	EXECUTE stmt;
	SET @olaDelBoDepDirPlr=CONCAT(" delete boDep  from st_ola_bo_direct_plr_deposit boDep inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boDep.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_PLR' " );
	PREPARE stmt FROM @olaDelBoDepDirPlr;
	EXECUTE stmt;
	SET @olaBoDepRefDirPlr=CONCAT("insert into ",archDBName,".st_ola_bo_direct_plr_deposit_refund select * from  st_ola_bo_direct_plr_deposit_refund where transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND_PLR' )" );
	PREPARE stmt FROM @olaBoDepRefDirPlr;
	EXECUTE stmt;
	SET @olaDelBoDepRefDirPlr=CONCAT("delete  boDepRef from    st_ola_bo_direct_plr_deposit_refund boDepRef inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boDepRef.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_DEPOSIT_REFUND_PLR' " );
	PREPARE stmt FROM @olaDelBoDepRefDirPlr;
	EXECUTE stmt;
	SET @olaBoWithDirPlr=CONCAT("insert into ",archDBName,".st_ola_bo_direct_plr_withdrawl select * from  st_ola_bo_direct_plr_withdrawl where transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL_PLR' )" );
	PREPARE stmt FROM @olaBoWithDirPlr;
	EXECUTE stmt;
	SET @olaDelBoWithDirPlr=CONCAT("delete boWith from  st_ola_bo_direct_plr_withdrawl boWith inner  join st_lms_bo_transaction_master slbm on slbm.transaction_id=boWith.transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type='OLA_WITHDRAWL_PLR' " );
	PREPARE stmt FROM @olaDelBoWithDirPlr;
	EXECUTE stmt;
	SET @olaWdrwlTmp=CONCAT("insert into ",archDBName,".st_ola_withdrawl_temp select * from  st_ola_withdrawl_temp where ref_transaction_id in(select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type in ('OLA_WITHDRAWL_PLR', 'OLA_WITHDRAWL') UNION select transaction_id  from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type in ('OLA_WITHDRAWL_PLR', 'OLA_WITHDRAWL') UNION select transaction_id  from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type in ('OLA_WITHDRAWL_PLR', 'OLA_WITHDRAWL'))" );
	PREPARE stmt FROM @olaWdrwlTmp;
	EXECUTE stmt;
	SET @olaDelWdrwlTmp=CONCAT("delete withTmp FROM st_ola_withdrawl_temp withTmp inner  join (select transaction_id, transaction_date from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type in ('OLA_WITHDRAWL_PLR', 'OLA_WITHDRAWL') UNION select transaction_id, transaction_date from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type in ('OLA_WITHDRAWL_PLR', 'OLA_WITHDRAWL') UNION select transaction_id, transaction_date from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'  and transaction_type in ('OLA_WITHDRAWL_PLR', 'OLA_WITHDRAWL')) txnTabls on txnTabls.transaction_id=withTmp.ref_transaction_id where txnTabls.transaction_date>='",startDate,"' and txnTabls.transaction_date<='",endDate,"'");
	PREPARE stmt FROM @olaDelWdrwlTmp;
	EXECUTE stmt;
	
	
END IF;	
SELECT 'ola DONE';
	SET @isDG:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='DG');
	IF(@isDG=1) THEN 
	  OPEN  gameDGCur;
	    read_loop: LOOP
		FETCH  gameDGCur INTO gameId;
		    IF done THEN
		      LEAVE read_loop;
		    END IF;
		SET @dg_sale=CONCAT("insert into ",archDBName,".st_dg_ret_sale_",gameId," select sale.transaction_id, sale.game_id, ticket_nbr, mrp_amt, retailer_comm, net_amt, agent_comm, agent_net_amt, sale.retailer_org_id, claim_status, good_cause_amt, agent_ref_transaction_id, vat_amt, taxable_sale,player_mob_number,ret_sd_amt,agt_vat_amt from st_dg_ret_sale_",gameId," sale inner join st_lms_retailer_transaction_master rtm on sale.transaction_id=rtm.transaction_id where sale.game_id=",gameId,"  and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('dg_sale','DG_SALE_OFFLINE')");    
		PREPARE stmt FROM @dg_sale;
	 	EXECUTE stmt;
		SET @dg_sale_del=CONCAT("delete sale from st_dg_ret_sale_",gameId," sale inner join st_lms_retailer_transaction_master rtm on sale.transaction_id=rtm.transaction_id where sale.game_id=",gameId,"  and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('dg_sale','DG_SALE_OFFLINE')");
		
		PREPARE stmt FROM @dg_sale_del;
	 	EXECUTE stmt;
		SET @dg_ref=CONCAT("insert into ",archDBName,".st_dg_ret_sale_refund_",gameId,"  select * from st_dg_ret_sale_refund_",gameId," where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where game_id=",gameId,"  and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @dg_ref;
 		EXECUTE stmt;
		SET @dg_ref_del=CONCAT("delete sale from st_dg_ret_sale_refund_",gameId," sale inner join st_lms_retailer_transaction_master rtm on sale.transaction_id=rtm.transaction_id where sale.game_id=",gameId,"  and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED')");
		PREPARE stmt FROM @dg_ref_del;
 		EXECUTE stmt;
       
		SET @dg_pwt=CONCAT("insert into ",archDBName,".st_dg_ret_pwt_",gameId," select * from st_dg_ret_pwt_",gameId," where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where game_id=",gameId," and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='dg_pwt' )");
		PREPARE stmt FROM @dg_pwt;
		EXECUTE stmt;
 
		
		SET @dg_pwt_del=CONCAT("delete pwt from st_dg_ret_pwt_",gameId," pwt inner join st_lms_retailer_transaction_master rtm on pwt.transaction_id=rtm.transaction_id where rtm.game_id=",gameId," and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='dg_pwt'");
		PREPARE stmt FROM @dg_pwt_del;
		EXECUTE stmt;
		SET @dg_pwt_inv=CONCAT("insert into ",archDBName,".st_dg_pwt_inv_",gameId," (ticket_nbr, draw_id, panel_id,pwt_amt,status,retailer_transaction_id,agent_transaction_id,bo_transaction_id,is_direct_plr) select ticket_nbr, draw_id, panel_id,pwt_amt,status,retailer_transaction_id,agent_transaction_id,bo_transaction_id,is_direct_plr from st_dg_pwt_inv_",gameId," inner join st_lms_retailer_transaction_master rtm on retailer_transaction_id=transaction_id where rtm.game_id=",gameId," and  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='DG_PWT' union select ticket_nbr, draw_id, panel_id,pwt_amt,status,retailer_transaction_id,agent_transaction_id,bo_transaction_id,is_direct_plr from st_dg_pwt_inv_",gameId," inner join st_lms_agent_transaction_master atm on agent_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_PWT_AUTO','DG_PWT_PLR') union select ticket_nbr, draw_id, panel_id,pwt_amt,status,retailer_transaction_id,agent_transaction_id,bo_transaction_id,is_direct_plr from st_dg_pwt_inv_",gameId," inner join st_lms_bo_transaction_master btm on bo_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_PWT_AUTO','DG_PWT_PLR')");
		PREPARE stmt FROM @dg_pwt_inv;
		EXECUTE stmt;
		SET @dg_pwt_inv_del=CONCAT("delete pwt from st_dg_pwt_inv_",gameId," pwt inner join st_lms_retailer_transaction_master rtm on retailer_transaction_id=rtm.transaction_id where rtm.game_id=",gameId," and  rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and rtm.transaction_type='DG_PWT'");
	
		PREPARE stmt FROM @dg_pwt_inv_del;
		EXECUTE stmt;
		SET @dg_pwt_inv_del=CONCAT("delete pwt from st_dg_pwt_inv_",gameId," pwt inner join st_lms_agent_transaction_master atm on agent_transaction_id=atm.transaction_id where atm.transaction_date>='",startDate,"' and atm.transaction_date<='",endDate,"' and atm.transaction_type in('DG_PWT_PLR', 'DG_PWT_AUTO')");
		PREPARE stmt FROM @dg_pwt_inv_del;
		EXECUTE stmt;
		SET @dg_pwt_inv_del=CONCAT("delete pwt from st_dg_pwt_inv_",gameId," pwt inner join st_lms_bo_transaction_master btm on bo_transaction_id=btm.transaction_id where btm.transaction_date>='",startDate,"' and btm.transaction_date<='",endDate,"' and btm.transaction_type in('DG_PWT_PLR', 'DG_PWT_AUTO')");
		PREPARE stmt FROM @dg_pwt_inv_del;
		EXECUTE stmt;
		SET @st_dg_printed_tickets=CONCAT("insert into ",archDBName,".st_dg_printed_tickets_",gameId,"  select * from st_dg_printed_tickets_",gameId," where notification_time>='",startDate,"' and notification_time<='",endDate,"'");
		PREPARE stmt FROM @st_dg_printed_tickets;
 		EXECUTE stmt;
		SET @st_dg_printed_tickets_del=CONCAT("delete from st_dg_printed_tickets_",gameId," where notification_time>='",startDate,"' and notification_time<='",endDate,"'");
		PREPARE stmt FROM @st_dg_printed_tickets_del;
 		EXECUTE stmt;
	    END LOOP;
	  CLOSE gameDGCur;
		SET @st_dg_approval_req_master=CONCAT("insert into ",archDBName,".st_dg_approval_req_master select * from st_dg_approval_req_master where approval_date>='",startDate,"' and approval_date<='",endDate,"'");
		PREPARE stmt FROM @st_dg_approval_req_master;
		EXECUTE stmt;
		SET @st_dg_approval_req_master_del=CONCAT("delete from st_dg_approval_req_master where approval_date>='",startDate,"' and approval_date<='",endDate,"'");
		PREPARE stmt FROM @st_dg_approval_req_master_del;
		EXECUTE stmt;
		SET @st_dg_bo_agent_pwt_comm_variance_history=CONCAT("insert into ",archDBName,".st_dg_bo_agent_pwt_comm_variance_history select * from st_dg_bo_agent_pwt_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_dg_bo_agent_pwt_comm_variance_history;
		EXECUTE stmt;
		SET @st_dg_bo_agent_pwt_comm_variance_history_del=CONCAT("delete from st_dg_bo_agent_pwt_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_dg_bo_agent_pwt_comm_variance_history_del;
		EXECUTE stmt;
		SET @st_dg_bo_agent_sale_comm_variance_history=CONCAT("insert into ",archDBName,".st_dg_bo_agent_sale_comm_variance_history select * from st_dg_bo_agent_sale_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_dg_bo_agent_sale_comm_variance_history;
		EXECUTE stmt;
		SET @st_dg_bo_agent_sale_comm_variance_history_del=CONCAT("delete from st_dg_bo_agent_sale_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_dg_bo_agent_sale_comm_variance_history_del;
		EXECUTE stmt;
		SET @st_dg_bo_ticket_cancel=CONCAT("insert into ",archDBName,".st_dg_bo_ticket_cancel select * from st_dg_bo_ticket_cancel where ret_trans_id in (select transaction_id from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @st_dg_bo_ticket_cancel;
		EXECUTE stmt;
		SET @st_dg_bo_ticket_cancel_del=CONCAT("delete from st_dg_bo_ticket_cancel where ret_trans_id in (select transaction_id from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @st_dg_bo_ticket_cancel_del;
		EXECUTE stmt;
		SET @st_dg_agt_sale=CONCAT("insert into ",archDBName,".st_dg_agt_sale select * from st_dg_agt_sale where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='DG_SALE')");
		PREPARE stmt FROM @st_dg_agt_sale;
		EXECUTE stmt;
		SET @st_dg_agt_sale_del=CONCAT("delete from st_dg_agt_sale where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='DG_SALE')");
		PREPARE stmt FROM @st_dg_agt_sale_del;
		EXECUTE stmt;
		SET @st_dg_agt_pwt=CONCAT(" insert into ",archDBName,".st_dg_agt_pwt select * from st_dg_agt_pwt where transaction_id in (select transaction_id from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type IN('DG_PWT_AUTO','DG_PWT_PLR'))");
		PREPARE stmt FROM @st_dg_agt_pwt;
		EXECUTE stmt;
		SET @st_dg_agt_pwt_del=CONCAT("delete from st_dg_agt_pwt where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type IN('DG_PWT_AUTO','DG_PWT_PLR'))");
		PREPARE stmt FROM @st_dg_agt_pwt_del;
		EXECUTE stmt;
		SET @st_dg_agt_direct_plr_pwt=CONCAT("insert into ",archDBName,".st_dg_agt_direct_plr_pwt select * from st_dg_agt_direct_plr_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and  transaction_type='DG_PWT_PLR' )");
		PREPARE stmt FROM @st_dg_agt_direct_plr_pwt;
		EXECUTE stmt;
		SET @st_dg_agt_direct_plr_pwt=CONCAT("delete from st_dg_agt_direct_plr_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and  transaction_type='DG_PWT_PLR' )");
		PREPARE stmt FROM @st_dg_agt_direct_plr_pwt;
		EXECUTE stmt;
		SET @st_dg_agt_sale_refund=CONCAT(" insert into ",archDBName,".st_dg_agt_sale_refund select * from st_dg_agt_sale_refund where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @st_dg_agt_sale_refund;
		EXECUTE stmt;
		SET @st_dg_agt_sale_refund=CONCAT("delete from st_dg_agt_sale_refund where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @st_dg_agt_sale_refund;
		EXECUTE stmt;
		SET @st_dg_bo_sale=CONCAT(" insert into ",archDBName,".st_dg_bo_sale select * from st_dg_bo_sale where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='dg_sale' )");
		PREPARE stmt FROM @st_dg_bo_sale;
		EXECUTE stmt;
		SET @st_dg_bo_sale=CONCAT("delete from st_dg_bo_sale where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='dg_sale' )");
		PREPARE stmt FROM @st_dg_bo_sale;
		EXECUTE stmt;
		SET @st_dg_bo_pwt=CONCAT(" insert into ",archDBName,".st_dg_bo_pwt select * from st_dg_bo_pwt where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type ='DG_PWT_AUTO')");
		PREPARE stmt FROM @st_dg_bo_pwt;
		EXECUTE stmt;
		SET @st_dg_bo_pwt=CONCAT("delete from st_dg_bo_pwt where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type ='DG_PWT_AUTO')");
		PREPARE stmt FROM @st_dg_bo_pwt;
		EXECUTE stmt;
		SET @st_dg_bo_sale_refund=CONCAT("insert into ",archDBName,".st_dg_bo_sale_refund   select * from st_dg_bo_sale_refund where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @st_dg_bo_sale_refund;
		EXECUTE stmt;
		SET @st_dg_bo_sale_refund=CONCAT("delete from st_dg_bo_sale_refund where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DG_REFUND_CANCEL','DG_REFUND_FAILED'))");
		PREPARE stmt FROM @st_dg_bo_sale_refund;
		EXECUTE stmt;
		SET @st_dg_bo_direct_plr_pwt=CONCAT(" insert into ",archDBName,".st_dg_bo_direct_plr_pwt    select * from st_dg_bo_direct_plr_pwt where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and  transaction_type='DG_PWT_PLR' )");
		PREPARE stmt FROM @st_dg_bo_direct_plr_pwt;
		EXECUTE stmt;
		SET @st_dg_bo_direct_plr_pwt=CONCAT("delete from st_dg_bo_direct_plr_pwt where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and  transaction_type='DG_PWT_PLR' )");
		PREPARE stmt FROM @st_dg_bo_direct_plr_pwt;
		EXECUTE stmt;
	END IF;
SELECT 'dg done';
SET done=0;
	SET @isCS:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='CS');
	IF(@isCS=1) THEN 
	
	  OPEN  catCSCur;
	    read_loop: LOOP
		FETCH  catCSCur INTO gameId;
		    IF done THEN
		      LEAVE read_loop;
		    END IF;
			SET @retCSSale=CONCAT("insert into ",archDBName,".st_cs_sale_",gameId," select * from st_cs_sale_",gameId," where transaction_id in (select transaction_id  from st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CS_SALE')");
			PREPARE stmt FROM @retCSSale;
			EXECUTE stmt;
			SET @delRetCSSale=CONCAT("delete from st_cs_sale_",gameId," where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CS_SALE')");
			PREPARE stmt FROM @delRetCSSale;
			EXECUTE stmt;
			SET @retCSRefund=CONCAT("insert into ",archDBName,".st_cs_refund_",gameId," select * from st_cs_refund_",gameId," where transaction_id in (select transaction_id  from st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CS_CANCEL_SERVER','CS_CANCEL_RET'))");
			PREPARE stmt FROM @retCSRefund;
			EXECUTE stmt;
			SET @delRetCSRefund=CONCAT("delete from st_cs_refund_",gameId," where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CS_CANCEL_SERVER','CS_CANCEL_RET'))");
			PREPARE stmt FROM @delRetCSRefund;
			EXECUTE stmt;
		 END LOOP;
	  CLOSE catCSCur;
	
	SET @agtCSSale=CONCAT("insert into ",archDBName,".st_cs_agt_sale select * from st_cs_agt_sale where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CS_SALE')");
	PREPARE stmt FROM @agtCSSale;
	EXECUTE stmt;
	SET @delAgtCSSale=CONCAT("delete from st_cs_agt_sale where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CS_SALE')");
	PREPARE stmt FROM @delAgtCSSale;
	EXECUTE stmt;
	SET @agtCSRefund=CONCAT("insert into ",archDBName,".st_cs_agt_refund select * from st_cs_agt_refund where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CS_CANCEL_SERVER','CS_CANCEL_RET'))");
	PREPARE stmt FROM @agtCSRefund;
	EXECUTE stmt;
	SET @delAgtCSRefund=CONCAT("delete from st_cs_agt_refund where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CS_CANCEL_SERVER','CS_CANCEL_RET'))");
	PREPARE stmt FROM @delAgtCSRefund;
	EXECUTE stmt;
	SET @boCSSale=CONCAT("insert into ",archDBName,".st_cs_bo_sale select * from st_cs_bo_sale where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CS_SALE')");
	PREPARE stmt FROM @boCSSale;
	EXECUTE stmt;
	SET @delBOCSSale=CONCAT("delete from st_cs_bo_sale where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CS_SALE')");
	PREPARE stmt FROM @delBOCSSale;
	EXECUTE stmt;
	SET @boCSRefund=CONCAT("insert into ",archDBName,".st_cs_bo_refund select * from st_cs_bo_refund where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CS_CANCEL_SERVER','CS_CANCEL_RET'))");
	PREPARE stmt FROM @boCSRefund;
	EXECUTE stmt;
	SET @delAgtCSRefund=CONCAT("delete from st_cs_bo_refund where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CS_CANCEL_SERVER','CS_CANCEL_RET'))");
	PREPARE stmt FROM @delAgtCSRefund;
	EXECUTE stmt;
    END IF;
SELECT 'cs done';
SET @isSE:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='SE');
IF(@isSE=1) THEN 
	SET @st_se_retailer_pwt=CONCAT("insert into ",archDBName,".st_se_retailer_pwt select * from st_se_retailer_pwt where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='pwt')");
	PREPARE stmt FROM @st_se_retailer_pwt;
	EXECUTE stmt;
	SET @st_se_retailer_pwt=CONCAT("delete from st_se_retailer_pwt where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='pwt')");
	PREPARE stmt FROM @st_se_retailer_pwt;
	EXECUTE stmt;
	SET @st_se_agent_pwt=CONCAT(" insert into ",archDBName,".st_se_agent_pwt select * from st_se_agent_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in('PWT_AUTO','PWT') )");
	PREPARE stmt FROM @st_se_agent_pwt;
	EXECUTE stmt;
	SET @st_se_agent_pwt=CONCAT("delete from st_se_agent_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in('PWT_AUTO','PWT') )");
	PREPARE stmt FROM @st_se_agent_pwt;
	EXECUTE stmt;
	SET @st_se_agt_direct_player_pwt=CONCAT(" insert into ",archDBName,".st_se_agt_direct_player_pwt select * from st_se_agt_direct_player_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and     transaction_type='PWT_PLR' )");
	PREPARE stmt FROM @st_se_agt_direct_player_pwt;
	EXECUTE stmt;
	SET @st_se_agt_direct_player_pwt=CONCAT("delete from st_se_agt_direct_player_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and     transaction_type='PWT_PLR' )");
	PREPARE stmt FROM @st_se_agt_direct_player_pwt;
	EXECUTE stmt;
	SET @st_se_supplier_bo_transaction=CONCAT(" insert into ",archDBName,".st_se_supplier_bo_transaction   select * from st_se_supplier_bo_transaction where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type ='PURCHASE')");
	PREPARE stmt FROM @st_se_supplier_bo_transaction;
	EXECUTE stmt;
	SET @st_se_supplier_bo_transaction=CONCAT("delete from st_se_supplier_bo_transaction where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type ='PURCHASE')");
	PREPARE stmt FROM @st_se_supplier_bo_transaction;
	EXECUTE stmt;
	SET @st_se_agent_retailer_transaction=CONCAT(" insert into ",archDBName,".st_se_agent_retailer_transaction select * from st_se_agent_retailer_transaction where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SALE_RET','sale') )");
	PREPARE stmt FROM @st_se_agent_retailer_transaction;
	EXECUTE stmt;
	SET @st_se_agent_retailer_transaction=CONCAT("delete from st_se_agent_retailer_transaction where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SALE_RET','sale') )");
	PREPARE stmt FROM @st_se_agent_retailer_transaction;
	EXECUTE stmt;
	SET @st_se_bo_agent_transaction=CONCAT(" insert into ",archDBName,".st_se_bo_agent_transaction    select * from st_se_bo_agent_transaction where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SALE_RET','SALE') )");
	PREPARE stmt FROM @st_se_bo_agent_transaction;
	EXECUTE stmt;
	SET @st_se_bo_agent_transaction=CONCAT("delete from st_se_bo_agent_transaction where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SALE_RET','SALE') )");
	PREPARE stmt FROM @st_se_bo_agent_transaction;
	EXECUTE stmt;
	SET @st_se_bo_pwt=CONCAT(" insert into ",archDBName,".st_se_bo_pwt    select * from st_se_bo_pwt where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in('PWT_AUTO','PWT'))");
	PREPARE stmt FROM @st_se_bo_pwt;
	EXECUTE stmt;
	SET @st_se_bo_pwt=CONCAT("delete from st_se_bo_pwt where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in('PWT_AUTO','PWT'))");
	PREPARE stmt FROM @st_se_bo_pwt;
	EXECUTE stmt;
	SET @st_se_direct_player_pwt=CONCAT(" insert into ",archDBName,".st_se_direct_player_pwt     select *  from st_se_direct_player_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and   transaction_type='PWT_PLR' )");
	PREPARE stmt FROM @st_se_direct_player_pwt;
	EXECUTE stmt;
	SET @st_se_direct_player_pwt=CONCAT("delete from st_se_direct_player_pwt where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and   transaction_type='PWT_PLR' )");
	PREPARE stmt FROM @st_se_direct_player_pwt;
	EXECUTE stmt;
END IF;
	SET @isSLE:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='SLE');
	IF(@isSLE=1) THEN 
		SET @sle_sale=CONCAT("insert into ",archDBName,".st_sle_ret_sale select * from st_sle_ret_sale where transaction_date>='",startDate,"' and transaction_date<='",endDate,"';");
		PREPARE stmt FROM @sle_sale;
	 	EXECUTE stmt;
		SET @sle_sale_del=CONCAT("delete sale from st_sle_ret_sale sale where transaction_date>='",startDate,"' and transaction_date<='",endDate,"';");
		PREPARE stmt FROM @sle_sale_del;
	 	EXECUTE stmt;
		SET @sle_ref=CONCAT("insert into ",archDBName,".st_sle_ret_sale_refund select * from st_sle_ret_sale_refund where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_REFUND_CANCEL','SLE_REFUND_FAILED'))");
		PREPARE stmt FROM @sle_ref;
 		EXECUTE stmt;
		SET @sle_ref_del=CONCAT("delete sale from st_sle_ret_sale_refund sale inner join st_lms_retailer_transaction_master rtm on sale.transaction_id=rtm.transaction_id where rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and transaction_type in ('SLE_REFUND_CANCEL','SLE_REFUND_FAILED')");
		PREPARE stmt FROM @sle_ref_del;
 		EXECUTE stmt;
       
		SET @sle_pwt_ret=CONCAT("insert into ",archDBName,".st_sle_ret_pwt select * from st_sle_ret_pwt where transaction_id in (select transaction_id from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='SLE_PWT')");
		PREPARE stmt FROM @sle_pwt_ret;
		EXECUTE stmt;
		SET @sle_pwt_ret_del=CONCAT("delete pwt from st_sle_ret_pwt pwt inner join st_lms_retailer_transaction_master rtm on pwt.transaction_id=rtm.transaction_id where rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and transaction_type='SLE_PWT'");
		PREPARE stmt FROM @sle_pwt_ret_del;
		EXECUTE stmt;
		SET @sle_pwt_inv=CONCAT("insert into ",archDBName,".st_sle_pwt_inv (game_id, game_type_id, draw_id, ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr) select inv.game_id, game_type_id, draw_id, ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr from st_sle_pwt_inv inv inner join st_lms_retailer_transaction_master rtm on retailer_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='SLE_PWT' union select game_id, game_type_id, draw_id, ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr from st_sle_pwt_inv inner join st_lms_agent_transaction_master atm on agent_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_PWT','SLE_PWT_AUTO','SLE_PWT_PLR') union select game_id, game_type_id, draw_id, ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr from st_sle_pwt_inv inner join st_lms_bo_transaction_master btm on bo_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_PWT_AUTO','SLE_PWT_PLR')");
		PREPARE stmt FROM @sle_pwt_inv;
		EXECUTE stmt;
		SET @sle_pwt_inv_del=CONCAT("delete pwt from st_sle_pwt_inv pwt inner join st_lms_retailer_transaction_master rtm on retailer_transaction_id=rtm.transaction_id where rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and rtm.transaction_type='SLE_PWT'");
		PREPARE stmt FROM @sle_pwt_inv_del;
		EXECUTE stmt;
		SET @sle_pwt_inv_del=CONCAT("delete pwt from st_sle_pwt_inv pwt inner join st_lms_agent_transaction_master atm on agent_transaction_id=atm.transaction_id where atm.transaction_date>='",startDate,"' and atm.transaction_date<='",endDate,"' and atm.transaction_type in('SLE_PWT','SLE_PWT_AUTO','SLE_PWT_PLR')");
		PREPARE stmt FROM @sle_pwt_inv_del;
		EXECUTE stmt;
		SET @sle_pwt_inv_del=CONCAT("delete pwt from st_sle_pwt_inv pwt inner join st_lms_bo_transaction_master btm on bo_transaction_id=btm.transaction_id where btm.transaction_date>='",startDate,"' and btm.transaction_date<='",endDate,"' and btm.transaction_type in('SLE_PWT_AUTO','SLE_PWT_PLR')");
		PREPARE stmt FROM @sle_pwt_inv_del;
		EXECUTE stmt;
		SET @st_sle_approval_req_master=CONCAT("insert into ",archDBName,".st_sle_approval_req_master select * from st_sle_approval_req_master where approval_date>='",startDate,"' and approval_date<='",endDate,"'");
		PREPARE stmt FROM @st_sle_approval_req_master;
		EXECUTE stmt;
		SET @st_sle_approval_req_master_del=CONCAT("delete from st_sle_approval_req_master where approval_date>='",startDate,"' and approval_date<='",endDate,"'");
		PREPARE stmt FROM @st_sle_approval_req_master_del;
		EXECUTE stmt;
		SET @st_sle_bo_agent_pwt_comm_variance_history=CONCAT("insert into ",archDBName,".st_sle_bo_agent_pwt_comm_variance_history select * from st_sle_bo_agent_pwt_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_sle_bo_agent_pwt_comm_variance_history;
		EXECUTE stmt;
		SET @st_sle_bo_agent_pwt_comm_variance_history_del=CONCAT("delete from st_sle_bo_agent_pwt_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_sle_bo_agent_pwt_comm_variance_history_del;
		EXECUTE stmt;
		SET @st_sle_bo_agent_sale_comm_variance_history=CONCAT("insert into ",archDBName,".st_sle_bo_agent_sale_comm_variance_history select * from st_sle_bo_agent_sale_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_sle_bo_agent_sale_comm_variance_history;
		EXECUTE stmt;
		SET @st_sle_bo_agent_sale_comm_variance_history_del=CONCAT("delete from st_sle_bo_agent_sale_comm_variance_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
		PREPARE stmt FROM @st_sle_bo_agent_sale_comm_variance_history_del;
		EXECUTE stmt;
		
		
		
		
		
		
		SET @st_sle_agt_sale=CONCAT("insert into ",archDBName,".st_sle_agt_sale select * from st_sle_agt_sale where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='SLE_SALE')");
		PREPARE stmt FROM @st_sle_agt_sale;
		EXECUTE stmt;
		SET @st_sle_agt_sale_del=CONCAT("delete from st_sle_agt_sale where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='SLE_SALE')");
		PREPARE stmt FROM @st_sle_agt_sale_del;
		EXECUTE stmt;
		SET @st_sle_agt_pwt=CONCAT("insert into ",archDBName,".st_sle_agt_pwt select * from st_sle_agt_pwt where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type IN('SLE_PWT','SLE_PWT_AUTO','SLE_PWT_PLR'))");
		PREPARE stmt FROM @st_sle_agt_pwt;
		EXECUTE stmt;
		SET @st_sle_agt_pwt_del=CONCAT("delete from st_sle_agt_pwt where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type IN('SLE_PWT','SLE_PWT_AUTO','SLE_PWT_PLR'))");
		PREPARE stmt FROM @st_sle_agt_pwt_del;
		EXECUTE stmt;
		
		
		
		
		
		
		SET @st_sle_agt_sale_refund=CONCAT(" insert into ",archDBName,".st_sle_agt_sale_refund select * from st_sle_agt_sale_refund where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_REFUND_CANCEL','SLE_REFUND_FAILED'))");
		PREPARE stmt FROM @st_sle_agt_sale_refund;
		EXECUTE stmt;
		SET @st_sle_agt_sale_refund=CONCAT("delete from st_sle_agt_sale_refund where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_REFUND_CANCEL','SLE_REFUND_FAILED'))");
		PREPARE stmt FROM @st_sle_agt_sale_refund;
		EXECUTE stmt;
		SET @st_sle_bo_sale=CONCAT(" insert into ",archDBName,".st_sle_bo_sale select * from st_sle_bo_sale where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='SLE_SALE' )");
		PREPARE stmt FROM @st_sle_bo_sale;
		EXECUTE stmt;
		SET @st_sle_bo_sale=CONCAT("delete from st_sle_bo_sale where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='SLE_SALE' )");
		PREPARE stmt FROM @st_sle_bo_sale;
		EXECUTE stmt;
		SET @st_sle_bo_pwt=CONCAT("insert into ",archDBName,".st_sle_bo_pwt select * from st_sle_bo_pwt where transaction_id in (select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_PWT_AUTO','SLE_PWT_PLR'))");
		PREPARE stmt FROM @st_sle_bo_pwt;
		EXECUTE stmt;
		SET @st_sle_bo_pwt_del=CONCAT("delete from st_sle_bo_pwt where transaction_id in (select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_PWT_AUTO','SLE_PWT_PLR'))");
		PREPARE stmt FROM @st_sle_bo_pwt_del;
		EXECUTE stmt;
		SET @st_sle_bo_sale_refund=CONCAT("insert into ",archDBName,".st_sle_bo_sale_refund   select * from st_sle_bo_sale_refund where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_REFUND_CANCEL','SLE_REFUND_FAILED'))");
		PREPARE stmt FROM @st_sle_bo_sale_refund;
		EXECUTE stmt;
		SET @st_sle_bo_sale_refund=CONCAT("delete from st_sle_bo_sale_refund where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_REFUND_CANCEL','SLE_REFUND_FAILED'))");
		PREPARE stmt FROM @st_sle_bo_sale_refund;
		EXECUTE stmt;
		SET @st_sle_bo_direct_plr_pwt=CONCAT("insert into ",archDBName,".st_sle_bo_direct_plr_pwt select * from st_sle_bo_direct_plr_pwt where transaction_id in (select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_PWT_AUTO','SLE_PWT_PLR'))");
		PREPARE stmt FROM @st_sle_bo_direct_plr_pwt;
		EXECUTE stmt;
		SET @st_sle_bo_direct_plr_pwt_del=CONCAT("delete from st_sle_bo_direct_plr_pwt where transaction_id in (select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('SLE_PWT_AUTO','SLE_PWT_PLR'))");
		PREPARE stmt FROM @st_sle_bo_direct_plr_pwt_del;
		EXECUTE stmt;
	END IF;
SELECT 'SLE DONE';
	SET @isIW:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='IW');
	IF(@isIW=1) THEN 
		SET @iw_sale=CONCAT("insert into ",archDBName,".st_iw_ret_sale select * from st_iw_ret_sale where transaction_date>='",startDate,"' and transaction_date<='",endDate,"';");
		PREPARE stmt FROM @iw_sale;
	 	EXECUTE stmt;
		SET @iw_sale_del=CONCAT("delete sale from st_iw_ret_sale sale where transaction_date>='",startDate,"' and transaction_date<='",endDate,"';");
		PREPARE stmt FROM @iw_sale_del;
	 	EXECUTE stmt;
		SET @iw_ref=CONCAT("insert into ",archDBName,".st_iw_ret_sale_refund select * from st_iw_ret_sale_refund where transaction_id in (select transaction_id  from    st_lms_retailer_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_REFUND_CANCEL'))");
		PREPARE stmt FROM @iw_ref;
 		EXECUTE stmt;
		SET @iw_ref_del=CONCAT("delete sale from st_iw_ret_sale_refund sale inner join st_lms_retailer_transaction_master rtm on sale.transaction_id=rtm.transaction_id where rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and transaction_type in ('IW_REFUND_CANCEL')");
		PREPARE stmt FROM @iw_ref_del;
 		EXECUTE stmt;
       select 'iw1';
		SET @iw_pwt_ret=CONCAT("insert into ",archDBName,".st_iw_ret_pwt select * from st_iw_ret_pwt where transaction_id in (select transaction_id from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='IW_PWT')");
		PREPARE stmt FROM @iw_pwt_ret;
		EXECUTE stmt;
select 'iwq';
		SET @iw_pwt_ret_del=CONCAT("delete pwt from st_iw_ret_pwt pwt inner join st_lms_retailer_transaction_master rtm on pwt.transaction_id=rtm.transaction_id where rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and transaction_type='IW_PWT'");
		PREPARE stmt FROM @iw_pwt_ret_del;
		EXECUTE stmt;
select 'iww';
		SET @iw_pwt_inv=CONCAT("insert into ",archDBName,".st_iw_pwt_inv (game_id,   ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr) select inv.game_id,   ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr from st_iw_pwt_inv inv inner join st_lms_retailer_transaction_master rtm on retailer_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='IW_PWT' union select game_id,   ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr from st_iw_pwt_inv inner join st_lms_agent_transaction_master atm on agent_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_PWT') union select game_id,   ticket_nbr, pwt_amt, retailer_transaction_id, agent_transaction_id, bo_transaction_id, status, is_direct_plr from st_iw_pwt_inv inner join st_lms_bo_transaction_master btm on bo_transaction_id=transaction_id where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_PWT')");
		PREPARE stmt FROM @iw_pwt_inv;
select @iw_pwt_inv;
		EXECUTE stmt;
       select 'iw2';
		SET @iw_pwt_inv_del=CONCAT("delete pwt from st_iw_pwt_inv pwt inner join st_lms_retailer_transaction_master rtm on retailer_transaction_id=rtm.transaction_id where rtm.transaction_date>='",startDate,"' and rtm.transaction_date<='",endDate,"' and rtm.transaction_type='IW_PWT'");
		PREPARE stmt FROM @iw_pwt_inv_del;
		EXECUTE stmt;
	
			SET @st_iw_bo_direct_plr_pwt=CONCAT("insert into ",archDBName,".st_iw_bo_direct_plr_pwt select * from st_iw_bo_direct_plr_pwt where transaction_id in (select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_PWT_AUTO','IW_PWT_PLR'))");
		PREPARE stmt FROM @st_iw_bo_direct_plr_pwt;
		EXECUTE stmt;
		SET @st_iw_bo_direct_plr_pwt_del=CONCAT("delete from st_iw_bo_direct_plr_pwt where transaction_id in (select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_PWT_AUTO','IW_PWT_PLR'))");
		PREPARE stmt FROM @st_iw_bo_direct_plr_pwt_del;
		EXECUTE stmt; 
	SET @st_iw_agent_direct_plr_pwt=CONCAT("insert into ",archDBName,".st_iw_agent_direct_plr_pwt select * from st_iw_agent_direct_plr_pwt where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_PWT_AUTO','IW_PWT_PLR'))");
		PREPARE stmt FROM @st_iw_bo_direct_plr_pwt;
		EXECUTE stmt;
		SET @st_iw_agent_direct_plr_pwt_del=CONCAT("delete from st_iw_agent_direct_plr_pwt where transaction_id in (select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('IW_PWT','IW_PWT_AUTO'))");
		PREPARE stmt FROM @st_iw_agent_direct_plr_pwt_del;
		EXECUTE stmt; 
	END IF;
SELECT 'IW DONE';
SET @isMgmt:=(SELECT IF(STATUS='ACTIVE',1,0) FROM st_lms_service_master WHERE service_code='MGMT');
IF(@isMgmt=1) THEN
	SET @st_lms_tp_system_txn_mapping=CONCAT("INSERT INTO ",archDBName,".st_lms_tp_system_txn_mapping SELECT a.* FROM st_lms_tp_system_txn_mapping a INNER JOIN st_lms_tp_txn_details b ON a.lms_txn_id=b.retailer_trans_id WHERE transaction_date>='",startDate,"' AND transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_tp_system_txn_mapping;
	EXECUTE stmt;
	
	
	
	SET @st_lms_tp_system_txn_mapping_sel=CONCAT("SELECT @min_txn_id:=ifnull(MIN(min_txn_id),0), @max_txn_id:=ifnull(MAX(max_txn_id),0) FROM (SELECT MIN(transaction_id) min_txn_id, MAX(transaction_id) max_txn_id FROM st_lms_bo_transaction_master WHERE transaction_date>='",startDate,"' AND transaction_date<='",endDate,"' UNION ALL SELECT MIN(transaction_id) min_txn_id, MAX(transaction_id) max_txn_id FROM st_lms_agent_transaction_master WHERE transaction_date>='",startDate,"' AND transaction_date<='",endDate,"' UNION ALL SELECT MIN(transaction_id) min_txn_id, MAX(transaction_id) max_txn_id FROM st_lms_retailer_transaction_master WHERE transaction_date>='",startDate,"' AND transaction_date<='",endDate,"')aa;");
	PREPARE stmt FROM @st_lms_tp_system_txn_mapping_sel;
	EXECUTE stmt;
	SET @st_lms_tp_system_txn_mapping_del=CONCAT("DELETE FROM st_lms_tp_system_txn_mapping WHERE lms_txn_id>=",@min_txn_id," AND lms_txn_id<=",@max_txn_id,";");
	PREPARE stmt FROM @st_lms_tp_system_txn_mapping_del;
	EXECUTE stmt;
	SET @st_lms_tp_txn_details=CONCAT("insert into ",archDBName,".st_lms_tp_txn_details select * from st_lms_tp_txn_details where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_tp_txn_details;
	EXECUTE stmt;
	SET @st_lms_tp_txn_details_del=CONCAT("delete from st_lms_tp_txn_details where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_tp_txn_details_del;
	EXECUTE stmt;
	SET @st_lms_agent_sale_chq=CONCAT(" insert into ",archDBName,".st_lms_agent_sale_chq select * from st_lms_agent_sale_chq where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CHEQUE','CHQ_BOUNCE'))");
	PREPARE stmt FROM @st_lms_agent_sale_chq;
	EXECUTE stmt;
	SET @st_lms_agent_sale_chq=CONCAT("delete from st_lms_agent_sale_chq where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CHEQUE','CHQ_BOUNCE'))");
	PREPARE stmt FROM @st_lms_agent_sale_chq;
	EXECUTE stmt;
	SET @st_lms_agent_debit_note=CONCAT(" insert into ",archDBName,".st_lms_agent_debit_note select * from st_lms_agent_debit_note where transaction_id in(select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DR_NOTE','DR_NOTE_CASH'))");
	PREPARE stmt FROM @st_lms_agent_debit_note;
	EXECUTE stmt;
SET @st_lms_agent_debit_note=CONCAT("delete from st_lms_agent_debit_note where transaction_id in(select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DR_NOTE','DR_NOTE_CASH'))");
	PREPARE stmt FROM @st_lms_agent_debit_note;
	EXECUTE stmt;
	SET @st_lms_agent_govt_transaction=CONCAT(" insert into ",archDBName,".st_lms_agent_govt_transaction select * from st_lms_agent_govt_transaction where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('VAT','TDS','GOVT_COMM'))");
	PREPARE stmt FROM @st_lms_agent_govt_transaction;
	EXECUTE stmt;
SET @st_lms_agent_govt_transaction=CONCAT("delete from st_lms_agent_govt_transaction where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('VAT','TDS','GOVT_COMM'))");
	PREPARE stmt FROM @st_lms_agent_govt_transaction;
	EXECUTE stmt;
	SET @st_lms_agent_cash_transaction=CONCAT(" insert into ",archDBName,".st_lms_agent_cash_transaction select * from st_lms_agent_cash_transaction where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type= ('CASH'))");
	PREPARE stmt FROM @st_lms_agent_cash_transaction;
	EXECUTE stmt;
	SET @st_lms_agent_cash_transaction=CONCAT("delete from st_lms_agent_cash_transaction where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type= ('CASH'))");
	PREPARE stmt FROM @st_lms_agent_cash_transaction;
	EXECUTE stmt;
	SET @st_lms_agent_credit_note=CONCAT(" insert into ",archDBName,".st_lms_agent_credit_note select * from st_lms_agent_credit_note where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CR_NOTE_CASH' )");
	PREPARE stmt FROM @st_lms_agent_credit_note;
	EXECUTE stmt;
	SET @st_lms_agent_credit_note=CONCAT("delete from st_lms_agent_credit_note where transaction_id in (select transaction_id  from    st_lms_agent_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CR_NOTE_CASH' )");
	PREPARE stmt FROM @st_lms_agent_credit_note;
	EXECUTE stmt;
	SET @st_lms_bo_sale_chq=CONCAT(" insert into ",archDBName,".st_lms_bo_sale_chq select * from st_lms_bo_sale_chq where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CHEQUE','CHQ_BOUNCE'))");
	PREPARE stmt FROM @st_lms_bo_sale_chq;
	EXECUTE stmt;
SET @st_lms_bo_sale_chq=CONCAT("delete from st_lms_bo_sale_chq where transaction_id in (select transaction_id  from    st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('CHEQUE','CHQ_BOUNCE'))");
	PREPARE stmt FROM @st_lms_bo_sale_chq;
	EXECUTE stmt;
	SET @st_lms_bo_govt_transaction=CONCAT(" insert into ",archDBName,".st_lms_bo_govt_transaction select * from st_lms_bo_govt_transaction where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('VAT','TDS','GOVT_COMM'))");
	PREPARE stmt FROM @st_lms_bo_govt_transaction;
	EXECUTE stmt;
	SET @st_lms_bo_govt_transaction=CONCAT("delete from st_lms_bo_govt_transaction where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('VAT','TDS','GOVT_COMM'))");
	PREPARE stmt FROM @st_lms_bo_govt_transaction;
	EXECUTE stmt;
	SET @st_lms_bo_cash_transaction=CONCAT(" insert into ",archDBName,".st_lms_bo_cash_transaction select * from st_lms_bo_cash_transaction where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type= ('CASH'))");
	PREPARE stmt FROM @st_lms_bo_cash_transaction;
	EXECUTE stmt;
SET @st_lms_bo_cash_transaction=CONCAT("delete from st_lms_bo_cash_transaction where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type= ('CASH'))");
	PREPARE stmt FROM @st_lms_bo_cash_transaction;
	EXECUTE stmt;
	SET @st_lms_bo_bank_deposit_transaction=CONCAT(" insert into ",archDBName,".st_lms_bo_bank_deposit_transaction select * from st_lms_bo_bank_deposit_transaction where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='BANK_DEPOSIT')");
	PREPARE stmt FROM @st_lms_bo_bank_deposit_transaction;
	EXECUTE stmt;
	SET @st_lms_bo_bank_deposit_transaction=CONCAT("delete from st_lms_bo_bank_deposit_transaction where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='BANK_DEPOSIT')");
	PREPARE stmt FROM @st_lms_bo_bank_deposit_transaction;
	EXECUTE stmt;
	SET @st_lms_agent_bank_deposit_transaction=CONCAT(" insert into ",archDBName,".st_lms_agent_bank_deposit_transaction select * from st_lms_agent_bank_deposit_transaction where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='BANK_DEPOSIT')");
	PREPARE stmt FROM @st_lms_agent_bank_deposit_transaction;
	EXECUTE stmt;
	SET @st_lms_agent_bank_deposit_transaction=CONCAT("delete from st_lms_agent_bank_deposit_transaction where transaction_id in (select transaction_id  from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='BANK_DEPOSIT')");
	PREPARE stmt FROM @st_lms_agent_bank_deposit_transaction;
	EXECUTE stmt;
	SET @st_lms_bo_credit_note=CONCAT("insert into ",archDBName,".st_lms_bo_credit_note select * from st_lms_bo_credit_note where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CR_NOTE_CASH')");
	PREPARE stmt FROM @st_lms_bo_credit_note;
	EXECUTE stmt;
SET @st_lms_bo_credit_note=CONCAT("delete from st_lms_bo_credit_note where transaction_id in (select transaction_id  from st_lms_bo_transaction_master where  transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type='CR_NOTE_CASH')");
	PREPARE stmt FROM @st_lms_bo_credit_note;
	EXECUTE stmt;
	SET @st_lms_bo_debit_note=CONCAT("insert into ",archDBName,".st_lms_bo_debit_note select * from st_lms_bo_debit_note where transaction_id in(select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DR_NOTE','DR_NOTE_CASH'))");
	PREPARE stmt FROM @st_lms_bo_debit_note;
	EXECUTE stmt;
SET @st_lms_bo_debit_note=CONCAT("delete from st_lms_bo_debit_note where transaction_id in(select transaction_id  from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' and transaction_type in ('DR_NOTE','DR_NOTE_CASH'))");
	PREPARE stmt FROM @st_lms_bo_debit_note;
	EXECUTE stmt;
	
	SET @temp_retailer_id=CONCAT("insert into temp_arch_trans_retailer (trans_id) select transaction_id from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @temp_retailer_id;
	EXECUTE stmt;
	SET @temp_agent_id=CONCAT("insert into temp_arch_trans_agent (trans_id) select transaction_id from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @temp_agent_id;
	EXECUTE stmt;
	SET @temp_bo_id=CONCAT("insert into temp_arch_trans_bo (trans_id) select transaction_id from st_lms_bo_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @temp_bo_id;
	EXECUTE stmt;
	SET @temp_agent_receipt_id=CONCAT("insert into temp_arch_rec_agent (rec_id) select distinct receipt_id from st_lms_agent_receipts_trn_mapping inner join temp_arch_trans_agent on transaction_id=trans_id");
	PREPARE stmt FROM @temp_agent_receipt_id;
	EXECUTE stmt;
	
	SET @temp_bo_receipt_id=CONCAT("insert into temp_arch_rec_bo (rec_id) select distinct receipt_id from st_lms_bo_receipts_trn_mapping inner join temp_arch_trans_bo on transaction_id=trans_id");
	PREPARE stmt FROM @temp_bo_receipt_id;
	EXECUTE stmt; 
	
	SET @st_lms_ret_transaction_master=CONCAT(" insert into ",archDBName,".st_lms_retailer_transaction_master select * from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' ");
	PREPARE stmt FROM @st_lms_ret_transaction_master;
	EXECUTE stmt;
	SET @st_lms_ret_transaction_master=CONCAT("delete from st_lms_retailer_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"' ");
	PREPARE stmt FROM @st_lms_ret_transaction_master;
	EXECUTE stmt;
	SET @st_lms_agent_receipts_trn_mapping=CONCAT("insert into ",archDBName,".st_lms_agent_receipts_trn_mapping (receipt_id,transaction_id) select receipt_id,transaction_id from st_lms_agent_receipts_trn_mapping inner join temp_arch_rec_agent on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_agent_receipts_trn_mapping;
	EXECUTE stmt;
	SET @st_lms_agent_receipts_trn_mapping=CONCAT("delete st_lms_agent_receipts_trn_mapping  from st_lms_agent_receipts_trn_mapping inner join temp_arch_rec_agent on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_agent_receipts_trn_mapping;
	EXECUTE stmt;
	SET @st_lms_agent_receipts=CONCAT("insert into ",archDBName,".st_lms_agent_receipts (receipt_id, receipt_type, agent_org_id, party_id, party_type, generated_id, voucher_date) select  receipt_id, receipt_type, agent_org_id, party_id, party_type, generated_id, voucher_date from st_lms_agent_receipts inner join temp_arch_rec_agent on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_agent_receipts;
	EXECUTE stmt;
	SET @st_lms_agent_receipts=CONCAT("delete st_lms_agent_receipts from st_lms_agent_receipts inner join temp_arch_rec_agent on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_agent_receipts;
	EXECUTE stmt;
	SET @st_lms_receipts_master1=CONCAT("insert into ",archDBName,".st_lms_receipts_master (receipt_id,user_type) select receipt_id,user_type from st_lms_receipts_master inner join temp_arch_rec_agent on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_receipts_master1;
	EXECUTE stmt;
	SET @st_lms_receipts_master1=CONCAT("delete st_lms_receipts_master from st_lms_receipts_master inner join temp_arch_rec_agent on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_receipts_master1;
	EXECUTE stmt;
	SET @st_lms_agent_transaction_master=CONCAT("insert into ",archDBName,".st_lms_agent_transaction_master select * from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_agent_transaction_master;
	EXECUTE stmt;
	SET @st_lms_agent_transaction_master=CONCAT("delete from st_lms_agent_transaction_master where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_agent_transaction_master;
	EXECUTE stmt;
	SET @st_lms_bo_receipts_trn_mapping=CONCAT("insert into ",archDBName,".st_lms_bo_receipts_trn_mapping (receipt_id,transaction_id) select receipt_id,transaction_id from st_lms_bo_receipts_trn_mapping inner join temp_arch_rec_bo on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_bo_receipts_trn_mapping;
	EXECUTE stmt;
	SET @st_lms_bo_receipts_trn_mapping=CONCAT("delete st_lms_bo_receipts_trn_mapping from st_lms_bo_receipts_trn_mapping inner join temp_arch_rec_bo on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_bo_receipts_trn_mapping;
	EXECUTE stmt;
 
	SET @st_lms_bo_receipts=CONCAT("insert into ",archDBName,".st_lms_bo_receipts (receipt_id, receipt_type, party_id, party_type, generated_id) select  receipt_id, receipt_type, party_id, party_type, generated_id from st_lms_bo_receipts inner join temp_arch_rec_bo on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_bo_receipts;
	EXECUTE stmt;
	SET @st_lms_bo_receipts=CONCAT("delete st_lms_bo_receipts from st_lms_bo_receipts inner join temp_arch_rec_bo on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_bo_receipts;
	EXECUTE stmt;
	SET @st_lms_receipts_master2=CONCAT("insert into ",archDBName,".st_lms_receipts_master (receipt_id,user_type) select receipt_id,user_type from st_lms_receipts_master inner join temp_arch_rec_bo on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_receipts_master2;
	EXECUTE stmt;
	SET @st_lms_receipts_master2=CONCAT("delete st_lms_receipts_master from st_lms_receipts_master inner join temp_arch_rec_bo on receipt_id=rec_id");
	PREPARE stmt FROM @st_lms_receipts_master2;
	EXECUTE stmt;
	SET @st_lms_bo_transaction_master=CONCAT("insert into ",archDBName,".st_lms_bo_transaction_master select * from st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_bo_transaction_master;
	EXECUTE stmt;
	SET @st_lms_bo_transaction_master=CONCAT("delete from st_lms_bo_transaction_master where   transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_bo_transaction_master;
	EXECUTE stmt;
	SET @st_lms_transaction_master=CONCAT("insert into ",archDBName,".st_lms_transaction_master (transaction_id, user_type, service_code, interface) select transaction_id, user_type, service_code, interface from st_lms_transaction_master inner join (select trans_id from temp_arch_trans_bo union all select trans_id from temp_arch_trans_agent union all select trans_id from temp_arch_trans_retailer) a on transaction_id=trans_id");
	PREPARE stmt FROM @st_lms_transaction_master;
	EXECUTE stmt;
	SET @st_lms_transaction_master=CONCAT("delete st_lms_transaction_master from st_lms_transaction_master inner join (select trans_id from temp_arch_trans_bo union all select trans_id from temp_arch_trans_agent union all select trans_id from temp_arch_trans_retailer) a on transaction_id=trans_id");
	PREPARE stmt FROM @st_lms_transaction_master;
	EXECUTE stmt;
	SET @agtCurBalHistory=CONCAT("insert into st_lms_agent_current_balance_history_arch select * from st_lms_agent_current_balance_history where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @agtCurBalHistory;
	EXECUTE stmt;
	SET @boCurBalHistory=CONCAT("insert into st_lms_bo_current_balance_history_arch select * from st_lms_bo_current_balance_history where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @boCurBalHistory;
	EXECUTE stmt;
		
	SET @agtLedger=CONCAT(" insert into ",archDBName,".st_lms_agent_ledger select * from st_lms_agent_ledger where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @agtLedger;
	EXECUTE stmt;
	SET @agtLedger=CONCAT("delete from st_lms_agent_ledger where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @agtLedger;
	EXECUTE stmt;
	SET @agtCurBalHistory=CONCAT(" insert into ",archDBName,".st_lms_agent_current_balance_history select * from st_lms_agent_current_balance_history where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @agtCurBalHistory;
	EXECUTE stmt;
	SET @agtCurBalHistory=CONCAT("delete from st_lms_agent_current_balance_history where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @agtCurBalHistory;
	EXECUTE stmt;
	SET @boLedger=CONCAT(" insert into ",archDBName,".st_lms_bo_ledger select * from st_lms_bo_ledger where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @boLedger;
	EXECUTE stmt;
	SET @boLedger=CONCAT("delete from st_lms_bo_ledger where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @boLedger;
	EXECUTE stmt;
	
	SET @boCurBalHistory=CONCAT(" insert into ",archDBName,".st_lms_bo_current_balance_history select * from st_lms_bo_current_balance_history where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @boCurBalHistory;
	EXECUTE stmt;
	SET @boCurBalHistory=CONCAT("delete from st_lms_bo_current_balance_history where transaction_date>='",startDate,"' and transaction_date<='",endDate,"'");
	PREPARE stmt FROM @boCurBalHistory;
	EXECUTE stmt;
	SET @st_lms_organization_master_history=CONCAT("insert into ",archDBName,".st_lms_organization_master_history select * from st_lms_organization_master_history where change_time>='",startDate,"' and change_time<='",endDate,"'");
	PREPARE stmt FROM @st_lms_organization_master_history;
	EXECUTE stmt;
	SET @st_lms_organization_master_history_del=CONCAT("delete from st_lms_organization_master_history where change_time>='",startDate,"' and change_time<='",endDate,"'");
	PREPARE stmt FROM @st_lms_organization_master_history_del;
	EXECUTE stmt;
	SET @st_lms_password_history=CONCAT("insert into ",archDBName,".st_lms_password_history select * from st_lms_password_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
	PREPARE stmt FROM @st_lms_password_history;
	EXECUTE stmt;
	SET @st_lms_password_history_del=CONCAT("delete from st_lms_password_history where date_changed>='",startDate,"' and date_changed<='",endDate,"'");
	PREPARE stmt FROM @st_lms_password_history_del;
	EXECUTE stmt;
	SET @st_lms_rg_org_daily_tx_history=CONCAT("insert into ",archDBName,".st_lms_rg_org_daily_tx_history select * from st_lms_rg_org_daily_tx_history where date>='",startDate,"' and date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_rg_org_daily_tx_history;
	EXECUTE stmt;
	SET @st_lms_rg_org_daily_tx_history_del=CONCAT("delete from st_lms_rg_org_daily_tx_history where date>='",startDate,"' and date<='",endDate,"'");
	PREPARE stmt FROM @st_lms_rg_org_daily_tx_history_del;
	EXECUTE stmt;
	SET @st_lms_rg_org_weakly_tx_history=CONCAT("insert into ",archDBName,".st_lms_rg_org_weakly_tx_history select * from st_lms_rg_org_weakly_tx_history where enddate>='",startDate,"' and enddate<='",endDate,"'");
	PREPARE stmt FROM @st_lms_rg_org_weakly_tx_history;
	EXECUTE stmt;
	SET @st_lms_rg_org_weakly_tx_history_del=CONCAT("delete from st_lms_rg_org_weakly_tx_history where enddate>='",startDate,"' and enddate<='",endDate,"'");
	PREPARE stmt FROM @st_lms_rg_org_weakly_tx_history_del;
	EXECUTE stmt;
	SET @st_lms_cl_xcl_update_history=CONCAT("insert into ",archDBName,".st_lms_cl_xcl_update_history select * from st_lms_cl_xcl_update_history where date_time>='",startDate,"' and date_time<='",endDate,"'");
	PREPARE stmt FROM @st_lms_cl_xcl_update_history;
	EXECUTE stmt;
	SET @st_lms_cl_xcl_update_history_del=CONCAT("delete from st_lms_cl_xcl_update_history where date_time>='",startDate,"' and date_time<='",endDate,"'");
	PREPARE stmt FROM @st_lms_cl_xcl_update_history_del;
	EXECUTE stmt;
END IF;
SELECT 'DONE';
 END
#
