package com.cssl.ctp.il.wsdl.il_availability_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;
import com.cssl.ctp.il.xsd.availability_v1.AvailabilityRequestBodyType;
import com.cssl.ctp.il.xsd.availability_v1.AvailabilityResponseBodyType;
import com.cssl.ctp.il.xsd.csheaders_v1.RequestHeaderType;
import com.cssl.ctp.il.xsd.csheaders_v1.ResponseHeaderType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AvailabilityPortType_v1_0", targetNamespace = "http://ctp.cssl.com/il/wsdl/Availability-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AvailabilityPortTypeV10 {

	/**
	 * 
	 * @param requestBody
	 * @param responseHeader
	 * @param responseBody
	 * @param requestHeader
	 * @throws Fault
	 */
	@WebMethod(operationName = "Availability")
	public void availability(
			@WebParam(name = "RequestHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/Availability-v1.0", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
			@WebParam(name = "AvailabilityRequest", targetNamespace = "http://ctp.cssl.com/il/wsdl/Availability-v1.0", partName = "requestBody") AvailabilityRequestBodyType requestBody,
			@WebParam(name = "ResponseHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/Availability-v1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader,
			@WebParam(name = "AvailabilityResponse", targetNamespace = "http://ctp.cssl.com/il/wsdl/Availability-v1.0", mode = WebParam.Mode.OUT, partName = "responseBody") Holder<AvailabilityResponseBodyType> responseBody)
			throws Fault;

}
