package com.skilrock.ipe.instantprint;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.skilrock.lms.common.filter.LMSFilterDispatcher;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * InstantPrint service = new InstantPrint();
 * IInstantPrint portType = service.getInstantPrintServicePort();
 * portType.cancelTicketProcess(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "InstantPrint", targetNamespace = "http://instantPrint.ipe.skilrock.com/", wsdlLocation = "file:/home/neerajjain/neerajSoft/workSpaces/backUp/latest/workspace_new/LMS_Mgmt/WebRoot/wsdl/InstantPrint.wsdl")
public class InstantPrint extends Service {

	private final static URL INSTANTPRINT_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.skilrock.ipe.instantprint.InstantPrint.class
					.getName());
	private final static String wsdlLoc = LMSFilterDispatcher.getHOST()+"://"+LMSFilterDispatcher.webLink+LMSFilterDispatcher.getPORT()+LMSFilterDispatcher.projectName;
	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.skilrock.ipe.instantprint.InstantPrint.class
					.getResource(".");
			url = new URL(
					baseUrl,
					wsdlLoc+"/wsdl/InstantPrint.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: "+wsdlLoc+"/wsdl/InstantPrint.wsdl, retrying as a local file");
			logger.warning(e.getMessage());
		}
		System.out.println(url);
		INSTANTPRINT_WSDL_LOCATION = url;
	}

	public InstantPrint(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public InstantPrint() {
		super(INSTANTPRINT_WSDL_LOCATION, new QName(
				"http://instantPrint.ipe.skilrock.com/", "InstantPrint"));
	}

	/**
	 * 
	 * @return returns IInstantPrint
	 */
	@WebEndpoint(name = "InstantPrintServicePort")
	public IInstantPrint getInstantPrintServicePort() {
		return super.getPort(new QName("http://instantPrint.ipe.skilrock.com/",
				"InstantPrintServicePort"), IInstantPrint.class);
	}

}
