package com.cssl.ctp.il.wsdl.mobilevouchertopup_v1;

import javax.xml.ws.WebFault;
import com.cssl.ctp.il.xsd.infra_v1.FaultInfoType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "FaultInfo", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileVoucherTopUp-v1.0")
public class Fault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private FaultInfoType faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public Fault(String message, FaultInfoType faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public Fault(String message, FaultInfoType faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: com.cssl.ctp.il.xsd.infra_v1.FaultInfoType
	 */
	public FaultInfoType getFaultInfo() {
		return faultInfo;
	}

}
