package com.cssl.ctp.il.wsdl.mobilevouchertopup_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;
import com.cssl.ctp.il.xsd.csheaders_v1.RequestHeaderType;
import com.cssl.ctp.il.xsd.csheaders_v1.ResponseHeaderType;
import com.cssl.ctp.il.xsd.mobilevouchertopup_v1.MobileVoucherTopUpRequestBodyType;
import com.cssl.ctp.il.xsd.mobilevouchertopup_v1.MobileVoucherTopUpResponseBodyType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MobileVoucherTopUpPortType_v1_0", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileVoucherTopUp-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MobileVoucherTopUpPortTypeV10 {

	/**
	 * 
	 * @param requestBody
	 * @param responseHeader
	 * @param responseBody
	 * @param requestHeader
	 * @throws Fault
	 */
	@WebMethod(operationName = "MobileVoucherTopUp")
	public void mobileVoucherTopUp(
			@WebParam(name = "RequestHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileVoucherTopUp-v1.0", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
			@WebParam(name = "MobileVoucherTopUpRequest", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileVoucherTopUp-v1.0", partName = "requestBody") MobileVoucherTopUpRequestBodyType requestBody,
			@WebParam(name = "ResponseHeader", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileVoucherTopUp-v1.0", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader,
			@WebParam(name = "MobileVoucherTopUpResponse", targetNamespace = "http://ctp.cssl.com/il/wsdl/MobileVoucherTopUp-v1.0", mode = WebParam.Mode.OUT, partName = "responseBody") Holder<MobileVoucherTopUpResponseBodyType> responseBody)
			throws Fault;

}
