package com.skilrock.lms.api.drawGames;

import com.skilrock.lms.api.beans.TPKenoPurchaseBean;
import com.skilrock.lms.api.beans.TPLottoPurchaseBean;
//Generated by MyEclipse

public interface ILmsDrawGameService {
	
	
	public TPLottoPurchaseBean zimLottoBonusSale(TPLottoPurchaseBean bonusBallLottoBean);
	public TPKenoPurchaseBean kenoTwoSale(TPKenoPurchaseBean kenoPurchaseBean);
}